version: '3.8'

volumes:
  kafka_data:
  user_db_data:
  user_redis_data:
  room_db_data:
  vote_db_data:
  vote_redis_data:
  sse_redis_data:

services:
  # ---------- Kafka (KRaft) ----------
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_KRAFT_CLUSTER_ID: UfY-L4rCTByQ5LxOdPYf8A
      ALLOW_PLAINTEXT_LISTENER: "yes"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    depends_on:
      - kafka

  # ---------- Eureka ----------
  discovery-service:
    build: ./discovery-service
    image: discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    volumes:
      - ./discovery-service/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=local

  #########################################################
  #  user-service
  #########################################################
  user-db:
    image: mariadb:latest
    container_name: user-db
    ports:
      - "3309:3306"
    volumes:
      - user_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user-db
      MYSQL_USER: minguni
      MYSQL_PASSWORD: minguni

  user-redis:
    image: redis:latest
    container_name: user-redis
    ports:
      - "6381:6379"
    volumes:
      - user_redis_data:/data

  user-service:
    build: ./user-service
    image: user-service:latest
    container_name: user-service
    ports:
      - "8087:8087"
    depends_on: [ discovery-service, user-db, user-redis ]
    volumes:
      - ./user-service/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mariadb://user-db:3306/user-db
      - SPRING_DATA_REDIS_HOST=user-redis
      - SPRING_DATA_REDIS_PORT=6379
      - EUREKA_INSTANCE_HOSTNAME=user-service

  #########################################################
  #  room-service
  #########################################################
  room-db:
    image: mariadb:latest
    container_name: room-db
    ports:
      - "3306:3306"
    volumes:
      - room_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: room-db
      MYSQL_USER: minguni
      MYSQL_PASSWORD: minguni

  room-service:
    build: ./room-service
    image: room-service:latest
    container_name: room-service
    ports:
      - "8080:8080"
    depends_on: [ discovery-service, room-db ]
    volumes:
      - ./room-service/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - SPRING_DATASOURCE_URL=jdbc:mariadb://room-db:3306/room-db
      - EUREKA_INSTANCE_HOSTNAME=room-service

  #########################################################
  #  vote-service
  #########################################################
  vote-db:
    image: mariadb:latest
    container_name: vote-db
    ports:
      - "3307:3306"
    volumes:
      - vote_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vote-db
      MYSQL_USER: minguni
      MYSQL_PASSWORD: minguni

  vote-redis:
    image: redis:latest
    container_name: vote-redis
    ports:
      - "6379:6379"
    volumes:
      - vote_redis_data:/data

  vote-service:
    build: ./vote-service
    image: vote-service:latest
    container_name: vote-service
    ports:
      - "8082:8082"
    depends_on: [ discovery-service, vote-db, vote-redis ]
    volumes:
      - ./vote-service/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - SPRING_DATASOURCE_URL=jdbc:mariadb://vote-db:3306/vote-db
      - SPRING_DATA_REDIS_HOST=vote-redis
      - SPRING_DATA_REDIS_PORT=6379
      - EUREKA_INSTANCE_HOSTNAME=vote-service

  #########################################################
  #  sse-server
  #########################################################
  sse-redis:
    image: redis:latest
    container_name: sse-redis
    ports:
      - "6380:6379"
    volumes:
      - sse_redis_data:/data

  sse-service:
    build: ./client-connection-service
    image: sse-service:latest
    container_name: sse-service
    ports:
      - "8084:8084"
    depends_on: [ discovery-service, sse-redis ]
    volumes:
      - ./client-connection-service/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - SPRING_DATA_REDIS_HOST=sse-redis
      - SPRING_DATA_REDIS_PORT=6379
      - JAVA_OPTS=-Xms512m -Xmx1g
      - EUREKA_INSTANCE_HOSTNAME=sse-service

  #########################################################
  #  auth-service
  #########################################################
  auth-service:
    build: ./auth-service
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "8083:8083"
    depends_on: [ discovery-service ]
    volumes:
      - ./auth-service/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
      - JAVA_OPTS=-Xms512m -Xmx1g
      - EUREKA_INSTANCE_HOSTNAME=auth-service

  #########################################################
  #  gateway
  #########################################################
  gateway:
    build: ./gateway
    image: gateway:latest
    container_name: gateway
    ports:
      - "9000:9000"
    depends_on: [ discovery-service ]
    volumes:
      - ./gateway/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka
      - JAVA_OPTS=-Xms512m -Xmx1g
      - EUREKA_INSTANCE_HOSTNAME=gateway