spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vottega.info@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mariadb://localhost:3309/user-db
    username: minguni
    password: minguni
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6381
springdoc:
  swagger-ui:
    path: /api

server:
  port: 8087