spring:
  application:
    name: user-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: vottega.info@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mariadb://localhost:3309/user-db
    username: minguni
    password: minguni
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6381
  security:
    oauth2:
      client:
        registration:
          service-b:
            provider: auth-service
            client-id: ${USER_SERVICE_CLIENT_ID:user-service}
            client-secret: ${USER_SERVICE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: auth_service.read
        provider:
          auth-service:
            token-uri: lb://auth-service/oauth2/token
springdoc:
  swagger-ui:
    path: /api

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka